apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx-app
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 80
  selector:
    app: nginx-app